import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "@/sanity/lib/live";
import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar";
import "../globals.css";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <SidebarProvider>
            <SidebarInset>{children}</SidebarInset>

            <AppSidebar side="right" />

            {/* <FloatingDock />
            <SidebarToggle /> */}

            {/* Mode Toggle - Desktop: bottom right next to AI chat, Mobile: top right next to burger menu */}
            {/* <div className="fixed md:bottom-6 md:right-24 top-4 right-18 md:top-auto md:left-auto z-20">
              <div className="w-10 h-10 md:w-12 md:h-12">
                <ModeToggle />
              </div>
            </div> */}
          </SidebarProvider>

          {/* Live content API */}
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
